front/src/texts/texts.json, front/src/weekview/Weekview.js
Kinda hacky, but works. Uses stringified numbers to iterate through the weekdayShorthand locs.
=> Moved weekdayLocs to texts.json

front/src/tabletview/rangeofficer.js
Super simple 3 hour timer for keeping browser up to date
=> Add auto refresh.

front/src/dayview/Dayview.js, front/src/infoboxes/Infoboxes.js, front/src/monthview/Monthview.js, front/src/scheduling/Scheduling.css, front/src/tabletview/rangeofficer.js, front/src/texts/texts.json, front/src/upcomingsupervisions/LoggedIn.js, front/src/weekview/Weekview.js
Everything should be self-explanatory.
=> Compile warnings & language

back/config/config.js
=> extended mock schedule creation to 2021

front/src/edittracks/tracks.js, front/src/monthview/Monthview.js, front/src/scheduling/Scheduling.js, front/src/trackview/Trackview.js, front/src/upcomingsupervisions/LoggedIn.js, front/src/utils/Utils.js, front/src/weekview/Weekview.js
Adding keys, class => className, small changes.
=> Cleaning console

front/src/TrackStatistics/TrackStatistics.css, front/src/TrackStatistics/TrackStatistics.js, front/src/navbar/Nav.css, front/src/navbar/Nav.js, front/src/tabletview/rangeofficer.css, front/src/tabletview/rangeofficer.js, front/src/texts/texts.json
=> Tabletview UI improvements

back/controllers/rangeSupervision.js, back/mailer.js, back/package.json
The function looks super odd, but it works. should probably clean it up?
=> Fr12 email

.github/workflows/tests.yml
Run the frontend tests with github actions.
=> Run tests with github actions

front/src/api/api.js, front/src/navbar/FeedbackWindow.js, front/src/navbar/Nav.js, front/src/navbar/SupervisorNotification.js, front/src/profile/ProfileSettings.module.scss, front/src/profile/profilepages/ChangePassword.module.scss, front/src/profile/profilepages/changepassword.js, front/src/profile/profilesettings.js, front/src/shared.module.scss, front/src/texts/texts.json
Migrate from Class component to a Function component, update props
=> Refactor SupervisorNotification

front/src/api/api.js, front/src/navbar/FeedbackWindow.js, front/src/navbar/FeedbackWindow.module.scss, front/src/navbar/Nav.js, front/src/navbar/SupervisorNotification.js, front/src/profile/ProfileSettings.module.scss, front/src/profile/profilepages/ChangePassword.module.scss, front/src/profile/profilepages/changepassword.js, front/src/profile/profilesettings.js, front/src/shared.module.scss, front/src/texts/texts.json
Not a lot of changes: mainly use frontend api, move style definitions to scss-file.
=> Refactor FeedbackWindow

.github/workflows/build_docker.yml, Dockerfile, deploy/startup.sh
Workflow for creating docker image when tag starting with dev- is created and also when release is released.
=> Workflow for publishing docker images to ghcr

front/src/shared.module.scss, front/src/signin/SignIn.js, front/src/signin/SignIn.module.scss
Move styles into scss-file, remove debug function
=> Refactor SignIn

.github/workflows/build_docker.yml, Dockerfile, back/__tests__/changeOwnPassword.test.js, back/__tests__/user.test.js, deploy/startup.sh, front/src/shared.module.scss, front/src/signin/SignIn.js, front/src/signin/SignIn.module.scss
=> Testing back changeownpassword

back/__tests__/sign.test.js, back/models/user.js, back/services/user.js
- käyttäjää haetaan case-insensitive nimellä **vain kirjautumisessa**
- ehkä kömpelöä lisätä uusi models-funktio, mutta parempaa ei tullut mieleen
ILIKE: https://www.postgresql.org/docs/8.3/functions-matching.html
=> User name case insensitive query in login

back/__tests__/changeOwnPassword.test.js, back/__tests__/resetPassword.test.js, back/__tests__/sign.test.js, back/__tests__/trackSupervision.test.js, back/__tests__/user.test.js, back/models/__mocks__/trackSupervision.js, back/models/__mocks__/user.js
Tests for track supervision and refactoring tests.
=> Testing back track supervision

front/src/api/api.js
Add v4 scheduling bug fix. Changes done to front/src/api/api.js
=> Add v4 scheduling bug fix

front/src/TrackStatistics/TrackStatistics.js, front/src/tabletview/rangeofficer.js
Tablet view track status sequence updated.
=> Tablet view track status

front/src/texts/texts.json, front/src/upcomingsupervisions/LoggedIn.js
Frontti saapumisajan kysymiselle.
=> Feature timestamp

front/src/scheduling/Scheduling.js
Green sliders and alphabetical order
=> Update sliders alphabetical

front/src/navbar/Nav.test.js, front/src/usermanagement/UserManagementView.js
Updated UserManagementView from class to function. After conversion no bugs encountered during manual testing but now for some unknown reason the automatic tests fail.
=> changed UserManagementView to function

back/knex/development/migrations/20240314155937_update_range_supervision.js, back/middlewares/rangeSupervision.js, back/models/rangeSupervision.js, back/validators/rangeSupervision.js, front/src/scheduling/Scheduling.js, front/src/upcomingsupervisions/LoggedIn.js
Connects the frontend rangeofficer arrival time picker with the backend
=> Timestamp backend

back/controllers/infoMessage.js, back/controllers/user.js, back/knex/development/migrations/20240305115457_create_table_association_rangeofficers.js, back/middlewares/user.js, back/models/user.js, back/routes.js, back/services/user.js, back/validators/user.js, front/src/api/api.js, front/src/infoBox/AddInfo.js, front/src/infoBox/InfoBox.js, front/src/profile/profilepages/ChangePassword.module.scss, front/src/profile/profilepages/rangeofficers.js, front/src/shared.module.scss, front/src/texts/texts.json
Resolved missing timestamp feature commit from history
=> Resolved missing commits

back/server.js
Added message deletion routine, this also fixes the info message bug where old messages were shown
=> Added infomessage deletion routine to backend server.js

front/src/TrackStatistics/TrackStatistics.js, front/src/TrackStatistics/TrackStatistics.test.js, front/src/infoBox/AddInfo.js, front/src/raffle/raffle.js, front/src/tabletview/rangeofficer.js, front/src/tabletview/rangeofficer.test.js, front/src/usermanagement/UserManagementView.js, front/src/usermanagement/UserManagementView.test.js, front/src/weekview/Weekview.js
Sorted lists in infomessage, raffle and usermanagementview. Fixed bug in weekview where today button did nothing. Fixed all old frontend tests.
=> Fixed old unit tests, sorted lists, fixed minor bugs

back/controllers/daterange.js, front/src/weekview/Weekview.js, front/src/weekview/Weekview.module.scss
- Added UI improvement, where the weekview displays the set arrival time as eta
=> Add timestamp to weekview UI

back/mailer.js
Added domain name to mail transporter. Configured app password with customer to get email sending to work
=> Added domain name to mail transport, fixed mail bug

.github/workflows/backend_tests.yml, .github/workflows/frontend_tests.yml
Might be ok to run tests on all branches, but this should be an improvement. You should be able to trigger tests with a pull request to a major dev branch e.g. ('v7-develop')
=> Updated to run tests on push & pull requests on 'v**-develop' branches

.github/workflows/backend_tests.yml, .github/workflows/frontend_tests.yml
Removed old node versions from tests. Updated to Node 20.x
=> Git workflow update

front/src/scheduling/Scheduling.js
Korjattu radan lisätiedot kenttään kirjoitus aikataulunäkymästä.
=> handleNotice, enable writing

front/src/Devices/devices.js
Added a check to ensure only superusers can add, update or delete devices.
=> Only superuser can add, edit or delete devices

front/src/navbar/Nav.module.scss
- reduced height of the navigation bar 
- reduced max size of the logo and buttons
=> Smaller navigation bar

front/package-lock.json, front/package.json, front/src/App.test.js, front/src/ButtonComponent/ButtonComponent.test.js, front/src/Devices/devices.test.js, front/src/TrackStatistics/TrackStatistics.test.js, front/src/dayview/Dayview.test.js, front/src/edittracks/tracks.test.js, front/src/monthview/Monthview.test.js, front/src/navbar/FeedbackWindow.test.js, front/src/navbar/Nav.test.js, front/src/navbar/SuperVisorNotification.test.js, front/src/profile/tests/supervisions.test.js, front/src/resetPW/ResetPassword.test.js, front/src/scheduling/Scheduling.test.js, front/src/setupTests.js, front/src/signin/Signin.test.js, front/src/tabletview/rangeofficer.test.js, front/src/trackview/Trackview.test.js, front/src/upcomingsupervisions/LoggedIn.test.js, front/src/usermanagement/UserManagementView.test.js, front/src/utils/Utils.test.js, front/src/weekview/Weekview.test.js
Added/fixed api mocks for the failing unit tests
=> Fix front unit tests

.github/workflows/docker_build_back.yml, .github/workflows/docker_build_front.yml
Created git workflow for building front and backend Docker images
This will test that the build succeeds.
It would be relatively easy to push the images to docker hub, to use for deployment
=> Vo docker build

front/src/TrackStatistics/TrackStatistics.module.scss
- marginal deleted from trackContainer
=> + and - buttons location fixed in tabletview

front/src/EmailSettings/EmailSettings.js, front/src/EmailSettings/EmailSettings.scss, front/src/texts/texts.json
=> Fixed the layout in email settings view

front/src/tabletview/rangeofficer.js, front/src/texts/texts.json
Tablet view fixes when no range master is set in the scheduling view.
=> Tablet view fixes when no range master is set

README.md, production-compose.yaml, production-test-compose.yaml, test_env_variables.env
- Added 
- compose files for
- production deployment
- for integration testing
-  .env file template for production/testing
- Updated README
=> Vo production test

front/src/texts/texts.json
Pull Request Checklist
Code Quality
Code quality meets the standards [X]
Testing
I have tested the code and it works [X]
Version Control
The version control is up to standards[X]
Documentation**
Documentation is up to standards[X]
=> feat/ joo changed to kylla 

front/src/profile/profilepages/changepassword.tsx
Fixes translation bugs on change password form
=> Fix changepassword page errors

front/src/raffle/raffle.tsx
The bug that was causing crash on raffle edit found and fixed. Small change but big bug
=> Fix editing raffle association

front/src/api/api.js, front/src/pages/UserManagement/UserManagementView.tsx
=> Fix/ updateuser problem
